language: node_js
node_js:
- 8.6.0
deploy:
  provider: heroku
  app:
    develop: express-app-staging
    master: express-app-master
  skip_cleanup: true
  api_key:
    secure: MLAW5iSK+pbjECd9LoVjL2Dx0bK1y+uu1/hiKMt+6N/MjIENEiai4iBQ6Sld4diuzk1fq6fG5eYaXmrtEhJwzg3QGYrXGRV35hD5mdLPiMK+LjOo/k7NX8saoboi4mtR5edhEHF5QvsxvN5b0Eo1BHcTIKKS3FuSwDz9kzg3b2y80FNZcdU3qU8fDkzbKxiQ2kpoDht5pKnDPhiEz90aabiJZ4l+oihSCP8uh/h5srZieijYbZgV2R/bytK4WXRyIfPb5qaNS5dMebhsvVuSthGjepW2dq3OP3Cenur26Vge3jmHCk2Hk4o+9zOWxJ70ZFpyWc0hb+NzdqcN6eUJs2SZY+JWqlCEht2zU3qU3AOwBoSJU/XPBJdTodT3Qs71lkTr53sdt8HfQAREdfts2iJtQ3FCiQ2RsHc2VtmSCnR0AOuIBU/7cyO31qiA1/tS+Eme/Roe5/9WsPY6tVDk23kybynJAeTf6j6g9Mmz6+PGD+Od0WtUX+icrSOiMyoq2Nxs2b54VM2lKeWblE2QRFXAKxeffX4LD8HWo1fNDUrRG5RFyEHLwAuRu5E34WaHzg2AkGFeuMe8qhxP4QArwoXsdCBcklJCsUepQ8Us4HwcSWvIfkPix5WMgKLHxXHP8f53fmeu2YdpOUASvT61wpA4h94rkuEdAb1+Gfag1lM=
jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      && rm -rf ./coverage
